### ISSUE TITLE
Leaflet features ? 

### ISSUE THREAD

**Issue by collmomo** [OSMBuildings/GLMap#1]
I would love using this map on my prod server, however the interactivity is so limited. I tried using the 2.5d version with leaflet but the actual results are rather disapointing in comparison to what can be done with this map. 

I am therefore wondering if you guys are planning to add features such as
- Popup
- Markers
- GeoJson Polygons
- Polygons (circle, square, multipolygon)

Basically the interactive stuff that can be done with Leaflet because as of now, the 3d feature is nice but nothing can be done with it. I mean can't add a legend, or makers or event my own heatmap. 

Thanks for considering this feature suggestion.

**Comment by kekscom** [comment]
If you don't need the 3d buildings component, I strongly recommend to have a look into Mapbox GL.

Otherwise, it'll easily take a few months to add the features you're looking for in addition to OSM Buildings. This is beyond our capacity.

What we can do is some adaption to have the 3D version running with Leaflet.

If you're interested to support us in either effort, it's much appreciated.

**Comment by collmomo** [comment]
Thanks for the recommendation !

Leaflet is not a priority as that mapbox gl has a lot of nice features that I could consider adding. Adding 3d feature as a plugin for leaflet or Mapbox GL seems like a great idea.

It keeps the ability of the base map and theres the ability to toggle 3d mode.

**Comment by ghost** [comment]
hi，“Uncaught TypeError: GLMap.TileLayer is not a constructor“ ，what‘s wrong？glmap.tilelayer can't find. thanks.

**Comment by kekscom** [comment]
This project is no longer maintained. It'S code is now part of OSMBuildings viewer.
https://github.com/OSMBuildings/OSMBuildings
